# Generated by Django 2.2.6 on 2019-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0015_auto_20191022_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher', models.CharField(max_length=255, verbose_name='Диспетчер')),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('order_no', models.CharField(max_length=255, verbose_name='Заказ №')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'файл графика',
                'verbose_name_plural': 'файл графика',
                'ordering': ['dispatcher'],
            },
        ),
        migrations.CreateModel(
            name='SheduleFileError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher', models.CharField(max_length=255, verbose_name='Диспетчер')),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('error', models.CharField(max_length=255, verbose_name='Заказ №')),
            ],
            options={
                'verbose_name': 'файл графика с ошибками',
                'verbose_name_plural': 'файл графика с ошибками',
                'ordering': ['dispatcher'],
            },
        ),
    ]
